version: '2'
services:
  jforum-app:
    image: jforum
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jforum-mysql:3306/jforum?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://jforum-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jforum-elasticsearch:9200
    ports:
      - 8080:8080
  jforum-mysql:
    extends:
      file: mysql.yml
      service: jforum-mysql
  jforum-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jforum-elasticsearch
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
