version: '2'
services:
  jforum-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    # volumes:
    #     - ~/volumes/jhipster/jforum/elasticsearch/:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    # volumes:
    #     - ~/volumes/jhipster/elastic/elasticsearch/:/usr/share/elasticsearch/data/
    ports:
      - 5601:5601
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'ELASTICSEARCH_URL=http://jforum-elasticsearch:9200'
    depends_on:
      - jforum-elasticsearch
