version: '2'
services:
  keycloak:
    image: jboss/keycloak:6.0.1
    command:
      [
        '-b',
        '0.0.0.0',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
        '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
        '-Djboss.socket.binding.port-offset=1000',
      ]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - DB_VENDOR=MYSQL
      - DB_ADDR=keycloak-mysql
      - DB_PORT=3306
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - JDBC_PARAMS=characterEncoding=UTF-8&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    ports:
      - 9080:9080
      - 9443:9443
      - 10990:10990
    depends_on:
      - keycloak-mysql
  keycloak-mysql:
    image: mysql:8.0.16
    volumes:
      - ~/volumes/jhipster/test1/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=keycloak
      - MYSQL_DATABASE=keycloak
      - MYSQL_PASSWORD=keycloak
      - MYSQL_ROOT_PASSWORD=keycloak
      - MYSQL_ROOT_HOST="%"
    ports:
      - 3308:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
